### ISSUE TITLE
Problem about downloading processed data

### ISSUE THREAD

**Issue by Feiyu-Yao** [VVeiCao/Motion2VecSets#1]
Hi, wei

This job is quite amazing and thanks for your great job!

I am trying to replicate the experiment. But it seems quite hard for me to download the processed data. Downloading data from nextclould platform is quite slow and can easily fail. Would you mind upload the processed data to other platforms, for example, onedrive, google drive or baidudisk? Also, it will increase the download success rate if you can split the processed data into few parts and then upload. 

Meanwhile, it would be great if you can give some guidance on how to use data preparation scripts in /home/liang/m2v/dataset/dataset_generate.

Best wishes, 
Feiyu

**Comment by netbeifeng** [comment]
Hi Feiyu,

Thank you for reaching out and showing interest in our work.

Apologies for the inconvenience with accessing NextCloud. As an alternative, we have uploaded a backup on Google Drive. You can download it from [here](https://drive.google.com/drive/folders/1fjrkFgB793HH7--qtme-X4p2ZMVywRgF?usp=sharing).

Regarding guidance for data generation and processing, we're in the process of refining it. We aim to release a clean and well-documented version by next week. Once completed, we'll notify you here and close the issue.

Best regards,
Chang
