### ISSUE TITLE
Question about the pretrained models

### ISSUE THREAD

**Issue by JarrentWu1031** [VVeiCao/Motion2VecSets#3]
Hi, excellent work! It seems that the link for the pretrained models is empty. Could you please provide the ckpts? Thanks!

**Comment by VVeiCao** [comment]
Hi,

The checkpoints link is updated. You can also find it here:https://drive.google.com/drive/folders/1Fg7glEYe4Dy4i5aezTP-MIuiNClzDuMc?usp=sharing

Best,
Wei

**Comment by JarrentWu1031** [comment]
> Hi,
> 
> The checkpoints link is updated. You can also find it here:https://drive.google.com/drive/folders/1Fg7glEYe4Dy4i5aezTP-MIuiNClzDuMc?usp=sharing
> 
> Best, Wei

Thanks!
